<?php

function zmdate($date){
$datee = $date;
$daydate = date("z",$datee);
$yeardate = date("Y",$datee);
$yeartoday = date("Y",time());
$daytommorow = date("z",time()-86400);
$daynow = date("z",time());
$chyear = date("L",time());
if(time() <= $datee+0){
$text = "now";
}elseif(time() <= $datee+2){
$text = "1 second ago";
}elseif(time() <= $datee+4){
$text = "2 seconds ago";
}elseif(time() <= $datee+6){
$text = "3 seconds ago";
}elseif(time() <= $datee+8){
$text = "4 seconds ago";
}elseif(time() <= $datee+10){
$text = "5 seconds ago";
}elseif(time() <= $datee+12){
$text = "6 seconds ago";
}elseif(time() <= $datee+14){
$text = "7 seconds ago";
}elseif(time() <= $datee+16){
$text = "8 seconds ago";
}elseif(time() <= $datee+18){
$text = "9 seconds ago";
}elseif(time() <= $datee+20){
$text = "10 seconds ago";
}elseif(time() <= $datee+22){
$text = "11 seconds ago";
}elseif(time() <= $datee+24){
$text = "12 seconds ago";
}elseif(time() <= $datee+26){
$text = "13 seconds ago";
}elseif(time() <= $datee+28){
$text = "14 seconds ago";
}elseif(time() <= $datee+30){
$text = "15 seconds ago";
}elseif(time() <= $datee+32){
$text = "16 seconds ago";
}elseif(time() <= $datee+34){
$text = "17 seconds ago";
}elseif(time() <= $datee+36){
$text = "18 seconds ago";
}elseif(time() <= $datee+38){
$text = "19 seconds ago";
}elseif(time() <= $datee+40){
$text = "20 seconds ago";
}elseif(time() <= $datee+42){
    $text = "21 second ago";
    }elseif(time() <= $datee+44){
    $text = "22 seconds ago";
    }elseif(time() <= $datee+46){
    $text = "23 seconds ago";
    }elseif(time() <= $datee+48){
    $text = "24 seconds ago";
    }elseif(time() <= $datee+50){
    $text = "25 seconds ago";
    }elseif(time() <= $datee+52){
    $text = "26 seconds ago";
    }elseif(time() <= $datee+54){
    $text = "27 seconds ago";
    }elseif(time() <= $datee+56){
    $text = "28 seconds ago";
    }elseif(time() <= $datee+58){
    $text = "29 seconds ago";
}elseif(time() <= $datee+60){
$text = "30 seconds ago";
}elseif(time() <= $datee+62){
$text = "31 second ago";
}elseif(time() <= $datee+64){
$text = "32 seconds ago";
}elseif(time() <= $datee+66){
$text = "33 seconds ago";
}elseif(time() <= $datee+68){
$text = "34 seconds ago";
}elseif(time() <= $datee+70){
$text = "35 seconds ago";
}elseif(time() <= $datee+72){
$text = "36 seconds ago";
}elseif(time() <= $datee+74){
$text = "37 seconds ago";
}elseif(time() <= $datee+76){
$text = "38 seconds ago";
}elseif(time() <= $datee+78){
$text = "39 seconds ago";
}elseif(time() <= $datee+80){
$text = "40 seconds ago";
}elseif(time() <= $datee+82){
$text = "41 second ago";
}elseif(time() <= $datee+84){
$text = "42 seconds ago";
}elseif(time() <= $datee+86){
$text = "43 seconds ago";
}elseif(time() <= $datee+88){
$text = "44 seconds ago";
}elseif(time() <= $datee+90){
$text = "45 seconds ago";
}elseif(time() <= $datee+92){
$text = "46 seconds ago";
}elseif(time() <= $datee+94){
$text = "47 seconds ago";
}elseif(time() <= $datee+96){
$text = "48 seconds ago";
}elseif(time() <= $datee+98){
$text = "49 seconds ago";
}elseif(time() <= $datee+100){
$text = "50 seconds ago";
}elseif(time() <= $datee+102){
$text = "51 second ago";
}elseif(time() <= $datee+104){
$text = "52 seconds ago";
}elseif(time() <= $datee+106){
$text = "53 seconds ago";
}elseif(time() <= $datee+108){
$text = "54 seconds ago";
}elseif(time() <= $datee+110){
$text = "55 seconds ago";
}elseif(time() <= $datee+112){
$text = "56 seconds ago";
}elseif(time() <= $datee+114){
$text = "57 seconds ago";
}elseif(time() <= $datee+116){
$text = "58 seconds ago";
}elseif(time() <= $datee+118){
$text = "59 seconds ago";
}elseif(time() <= $datee+120){
$text = "minute ago";
}elseif(time() <= $datee+180){
$text = "2 minutes ago";
}elseif(time() <= $datee+240){
$text = "3 minutes ago";
}elseif(time() <= $datee+300){
$text = "4 minutes ago";
}elseif(time() <= $datee+360){
$text = "5 minutes ago";
}elseif(time() <= $datee+420){ 
$text = "6 minutes ago";       
}elseif(time() <= $datee+480){ 
$text = "7 minutes ago";	   
}elseif(time() <= $datee+540){
$text = "8 minutes ago";
}elseif(time() <= $datee+600){
$text = "9 minutes ago";
}elseif(time() <= $datee+660){
$text = "10 minutes ago";
}elseif(time() <= $datee+720){
$text = "11 minutes ago";
}elseif(time() <= $datee+780){
$text = "12 minutes ago";
}elseif(time() <= $datee+840){
$text = "13 minutes ago";
}elseif(time() <= $datee+900){
$text = "14 minutes ago";
}elseif(time() <= $datee+960){
$text = "15 minutes ago";
}elseif(time() <= $datee+1020){
$text = "16 minutes ago";
}elseif(time() <= $datee+1080){
$text = "17 minutes ago";
}elseif(time() <= $datee+1140){
$text = "18 minutes ago";
}elseif(time() <= $datee+1200){
$text = "19 minutes ago";
}elseif(time() <= $datee+1260){
$text = "20 minutes ago";
}elseif(time() <= $datee+1320){
$text = "21 minutes ago";
}elseif(time() <= $datee+1380){
$text = "22 minutes ago";
}elseif(time() <= $datee+1440){
$text = "23 minutes ago";
}elseif(time() <= $datee+1500){
$text = "24 minutes ago";
}elseif(time() <= $datee+1560){
$text = "25 minutes ago";
}elseif(time() <= $datee+1620){
$text = "26 minutes ago";
}elseif(time() <= $datee+1680){
$text = "27 minutes ago";
}elseif(time() <= $datee+1740){
$text = "28 minutes ago";
}elseif(time() <= $datee+1800){
$text = "29 minutes ago";
}elseif(time() <= $datee+1860){
$text = "30 minutes ago";
}elseif(time() <= $datee+1920){
$text = "31 minute ago";
}elseif(time() <= $datee+1980){
$text = "32 minutes ago";
}elseif(time() <= $datee+2040){
$text = "33 minutes ago";
}elseif(time() <= $datee+2100){
$text = "34 minutes ago";
}elseif(time() <= $datee+2160){
$text = "35 minutes ago";
}elseif(time() <= $datee+2220){
$text = "36 minutes ago";
}elseif(time() <= $datee+2280){
    $text = "37 minutes ago";
}elseif(time() <= $datee+2340){
    $text = "38 minutes ago";
}elseif(time() <= $datee+2400){
    $text = "39 minutes ago";
}elseif(time() <= $datee+2460){
    $text = "40 minutes ago";
}elseif(time() <= $datee+2520){
    $text = "41 minute ago";
}elseif(time() <= $datee+2580){
    $text = "42 minutes ago";
}elseif(time() <= $datee+2640){
    $text = "43 minutes ago";
}elseif(time() <= $datee+2700){
    $text = "44 minutes ago";
}elseif(time() <= $datee+2760){
    $text = "45 minutes ago";
}elseif(time() <= $datee+2820){
    $text = "46 minutes ago";
}elseif(time() <= $datee+2880){
    $text = "47 minutes ago";
}elseif(time() <= $datee+2940){
    $text = "48 minutes ago";
}elseif(time() <= $datee+3000){
    $text = "49 minutes ago";
}elseif(time() <= $datee+3060){
    $text = "50 minutes ago";
}elseif(time() <= $datee+3120){
    $text = "51 minute ago";
}elseif(time() <= $datee+3180){
    $text = "52 minutes ago";
}elseif(time() <= $datee+3240){
    $text = "53 minutes ago";
}elseif(time() <= $datee+3300){
    $text = "54 minutes ago";
}elseif(time() <= $datee+3360){
    $text = "55 minutes ago";
}elseif(time() <= $datee+3420){
    $text = "56 minutes ago";
}elseif(time() <= $datee+3480){
    $text = "57 minutes ago";
}elseif(time() <= $datee+3540){
    $text = "58 minutes ago";
}elseif(time() <= $datee+3600){
    $text = "59 minutes ago";
}elseif(time() <= $datee+3660){
    $text = "60 minutes ago";
}elseif($daynow == $daydate AND $yeardate == $yeartoday){
$text = "today in ".date("H:i",$datee);
}elseif ($daytommorow == $daydate AND $yeardate == $yeartoday) {
$text = "yesterday in ".date("H:i",$datee);
}else{
$text = date("d F Y ",$datee);
$text = str_replace("January","january",$text);
$text = str_replace("February","february",$text);
$text = str_replace("March","march",$text);
$text = str_replace("April","april",$text);
$text = str_replace("May","may",$text);
$text = str_replace("June","june",$text);
$text = str_replace("July","july",$text);
$text = str_replace("August","august",$text);
$text = str_replace("September","september",$text);
$text = str_replace("October","october",$text);
$text = str_replace("November","november",$text);
$text = str_replace("December","december",$text);
}
return $text; 
}

function zmbd($date){ 

$datee = $date;
$daydate = date("z",$datee);
$yeardate = date("Y",$datee);
$yeartoday = date("Y",time());
$daynow = date("z",time());
$chyear = date("L",time());
if(time() <= $datee+15){
$text = "now";
}elseif(time() <= $datee+120){
$text = "minute ago";
}elseif(time() <= $datee+180){
$text = "2 minutes ago";
}elseif(time() <= $datee+240){
$text = "3 minutes ago";
}elseif(time() <= $datee+300){
$text = "4 minutes ago";
}elseif(time() <= $datee+360){
$text = "5 minutes ago";
}elseif(time() <= $datee+420){ 
$text = "6 minutes ago";
}elseif(time() <= $datee+480){
$text = "7 minutes ago";
}elseif(time() <= $datee+540){
$text = "8 minutes ago";
}elseif(time() <= $datee+600){
$text = "9 minutes ago";
}elseif(time() <= $datee+660){
$text = "10 minutes ago";
}elseif(time() <= $datee+720){
$text = "11 minutes ago";
}elseif(time() <= $datee+780){
$text = "12 minutes ago";
}elseif(time() <= $datee+840){
$text = "13 minutes ago";
}elseif(time() <= $datee+900){
$text = "14 minutes ago";
}elseif(time() <= $datee+960){
$text = "15 minutes ago";
}elseif(time() <= $datee+1020){
$text = "16 minutes ago";
}elseif(time() <= $datee+1080){
$text = "17 minutes ago";
}elseif(time() <= $datee+1140){
$text = "18 minutes ago";
}elseif(time() <= $datee+1200){
$text = "19 minutes ago";
}elseif(time() <= $datee+1260){
$text = "20 minutes ago";
}elseif(time() <= $datee+1320){
$text = "21 minute ago";
}elseif(time() <= $datee+1380){
$text = "22 minutes ago";
}elseif(time() <= $datee+1440){
$text = "23 minutes ago";
}elseif(time() <= $datee+1500){
$text = "24 minutes ago";
}elseif(time() <= $datee+1560){
$text = "25 minutes ago";
}elseif(time() <= $datee+1620){
$text = "26 minutes ago";
}elseif(time() <= $datee+1680){
$text = "27 minutes ago";
}elseif(time() <= $datee+1740){
$text = "28 minutes ago";
}elseif(time() <= $datee+1800){
$text = "29 minutes ago";
}elseif(time() <= $datee+1860){
$text = "30 minutes ago";
}elseif($daynow == $daydate AND $yeardate == $yeartoday){
$text = "today in ".date("H:i",$datee);
}else{
$text = date("d F Y",$datee);
$text = str_replace("January","january",$text);
$text = str_replace("February","february",$text);
$text = str_replace("March","march",$text);
$text = str_replace("April","april",$text);
$text = str_replace("May","may",$text);
$text = str_replace("June","june",$text);
$text = str_replace("July","july",$text);
$text = str_replace("August","august",$text);
$text = str_replace("September","september",$text);
$text = str_replace("October","october",$text);
$text = str_replace("November","november",$text);
$text = str_replace("December","december",$text);
}
return $text; // 19 november 2002
}

function zmdateapi($date){ // дата для api
//$datee = $date - 284012334;
$datee = $date;
$text = date("d.n.Y",$datee);
return $text; // 8.10.2017
}

function zmd($date){ // дата , для блядской тусовки (сделал вова)
//$datee = $date - 284012334;
$datee = $date;
$daydate = date("z",$datee);
$daynow = date("z",time());
$chyear = date("L",time());
$daytommorow = date("z",time()-86400);
$dayyesterday = date("z",time()+86400);
if($daynow == $daydate){
$text = "today in ".date("H:i",$datee);
}elseif ($daytommorow == $daydate) {
$text = "yesterday in ".date("H:i",$datee);
}elseif ($dayyesterday == $daydate) {
$text = "tomorrow in ".date("H:i",$datee);
}else{
$text = date("d F Y ",$datee);
$text = str_replace("January","january",$text);
$text = str_replace("February","february",$text);
$text = str_replace("March","march",$text);
$text = str_replace("April","april",$text);
$text = str_replace("May","may",$text);
$text = str_replace("June","june",$text);
$text = str_replace("July","july",$text);
$text = str_replace("August","august",$text);
$text = str_replace("September","september",$text);
$text = str_replace("October","october",$text);
$text = str_replace("November","november",$text);
$text = str_replace("December","december",$text);

}
return $text;
}
?>